### ISSUE TITLE
Multiple links per project

### ISSUE THREAD

**Issue by toto** [nandorocker/evenly-web#7]
Currently we have only one app store link

We should have:
- At least Android and iOS links (both optional)
- An optional website link 
- those should be defined in the YAML of `_projects/.md` e.g.:

```
links: 
  - ios: http://foo.com
  - android: http://bar.com
  - web: http://baz.com
```
